sonar.projectKey=sajda-streaming-platform
sonar.projectName=sajda streaming slatform
sonar.host.url=http://localhost:30005
 
sonar.exclusions=README.md, package-lock.json, **/venv/**, **/__pycache__/**, **/.git/**


sonar.test.exclusions=CI-app/**/*

sonar.inclusions=**/*.py, **/*.yaml, **/*.yml, CI-app/docker-compose.yml, CI-app/package-lock.json, CI-app/package.json, CI-app/server.js
